config/routes.rb
MeantIt::Application.routes.draw do

  get "/group/:pii_value_input" => "home#group"

  get "/shops/:id" => "shops#show"
  post "/payments/ipn_pp_20111224" => "payments#ipn"
  get "/payments/pay/invoice_no/:invoice_no" => "payments#pay"
  get "/payments/invoice_no/:invoice_no" => "payments#show"
  get "/payments/cancel/invoice_no/:invoice_no" => "payments#cancel"

  resources :payments

  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "verify_captcha" => "sessions#verify_captcha", :as => "verify_captcha"
  get "manage" => "sessions#manage", :as => "manage"
  get "resend_confirmation" => "sessions#resend_confirmation", :as => "resend_confirmation"
  get "send_liker_emails" => "sessions#send_liker_emails"
  get "bill" => "sessions#bill_2", :as => "bill_2"
  get "bills/error" => "sessions#bills_error"

  devise_for :users, :controllers => { :confirmations => "meant_it_confirmations" }

  resources :sessions

  resources :pii_property_sets

  resources :inbound_email_logs

  resources :yes_emails

  resources :meant_it_mood_tag_rels

  resources :entity_data

  resources :inbound_emails

  resources :end_point_tag_rels

  resources :tags

  resources :obj_rels

  resources :meant_it_rels do
    collection do
      get 'show_out_by_pii'
      get 'count_in_mirs'
      get 'show_in_by_pii'
      get 'show_out_by_endpoint_nick/:nick/(:message_type)', :action => 'show_out_by_endpoint_nick'
      get 'show_in_by_endpoint_nick/:nick/(:message_type)', :action => 'show_in_by_endpoint_nick'
      get 'show_out_by_endpoint_id/:id/(:message_type)', :action => 'show_out_by_endpoint_id'
      get 'show_in_by_endpoint_id/:id/(:message_type)', :action => 'show_in_by_endpoint_id'
      get 'show_by_endpoint_endpoint_nick/:nick1/:nick2/(:message_type)', :action => 'show_by_endpoint_endpoint_nick'
      get 'show_by_pii_pii' 
      get 'show_by_pii_endpoint_nick'
      get 'show_by_endpoint_nick_pii'
      get 'show_by_message_type'
    end
  end

  resources :entity_end_point_rels

  resources :end_points do
    collection do
      get 'show_by_nick/:nick', :action => "show_by_nick"
      get 'find_by_nick_and_creator_endpoint_id'
      get 'show_by_nick_and_creator_endpoint_id'
      get 'find_by_tags'
      get 'show_by_tags'
      get "show_by_id/:id", :action => "show_by_id"
      get "show_by_ids"
    end
  end

  resources :entities

  get 'piis/pii_property_set_limited/:pii_value_input' => "piis#pii_property_set_limited"

  resources :piis do
    collection do
      get 'find_by_pii_value'
      get 'find_by_pii_value_debug'
      get 'show_by_pii_value'
      get 'show_by_pii_value_debug'
      get 'show_by_message_type_uniq_sender_count'
      get 'show_like_pii_value_uniq_sender_count_after_last_bill'
      get 'show_like_pii_value_non_uniq_sender_count_after_last_bill'
    end
  end

  resources :people

  get "home/index"

  root :to => "home#index"
  match "/why" => "home#why"
  match "/message_types" => "home#message_types"
  match "/learn_find" => "home#learn_find"
  match "/learn_send" => "home#learn_send"
  match "/tutorial_1" => "home#tutorial_1"
  match "/group.html" => "home#group"
  match "/group_old.html" => "home#group_old"
  match "/group_diy.html" => "home#group_diy"
  match "/cafeshopping.html" => "home#cafeshopping"
  match "/like.html" => "home#like"
  match "/platform.html" => "home#platform"
  match "/apis.html" => "home#apis"
  match "/policy.html" => "home#policy"
  match "/campaigns/:name" => "home#campaigns"
  match "/campaigns/:predir/:name" => "home#campaigns"

  match "/receive_email" => ReceiveEmail

  match "/find_any" => FindAny.action(:index)

  match "/inbound_emails_200" => "inbound_emails#create", :defaults => { :format => 'xml' }
  match "/send_inbound_emails" => "inbound_emails#create"

end

app/models/end_point_tag_rel.rb
require 'validators'

class EndPointTagRel < ActiveRecord::Base
#  belongs_to :endPoint, :class_name => "EndPoint", :foreign_key => '"endPoint_id"'
  belongs_to :endPoint, :class_name => "EndPoint", :foreign_key => "endpoint_id"
  belongs_to :tag

  validates :status, :presence => true, :status_type => true

  after_initialize :default_values

  private
    def default_values
      self.status||= StatusTypeValidator::STATUS_ACTIVE
    end
end

app/controllers/end_point_tag_rels_controller.rb
class EndPointTagRelsController < ApplicationController
  before_filter :authorize, :except => [:index, :show, :create ]

  # GET /end_point_tag_rels
  # GET /end_point_tag_rels.xml
  def index
    @end_point_tag_rels = EndPointTagRel.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @end_point_tag_rels }
    end
  end

  # GET /end_point_tag_rels/1
  # GET /end_point_tag_rels/1.xml
  def show
    @end_point_tag_rel = EndPointTagRel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @end_point_tag_rel }
    end
  end

  # GET /end_point_tag_rels/new
  # GET /end_point_tag_rels/new.xml
  def new
    @end_point_tag_rel = EndPointTagRel.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @end_point_tag_rel }
    end
  end

  # GET /end_point_tag_rels/1/edit
  def edit
    @end_point_tag_rel = EndPointTagRel.find(params[:id])
  end

  # POST /end_point_tag_rels
  # POST /end_point_tag_rels.xml
  def create
    @end_point_tag_rel = EndPointTagRel.new(params[:end_point_tag_rel])

    respond_to do |format|
      if @end_point_tag_rel.save
        format.html { redirect_to(@end_point_tag_rel, :notice => 'End point tag rel was successfully created.') }
        format.xml  { render :xml => @end_point_tag_rel, :status => :created, :location => @end_point_tag_rel }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @end_point_tag_rel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /end_point_tag_rels/1
  # PUT /end_point_tag_rels/1.xml
  def update
    @end_point_tag_rel = EndPointTagRel.find(params[:id])

    respond_to do |format|
      if @end_point_tag_rel.update_attributes(params[:end_point_tag_rel])
        format.html { redirect_to(@end_point_tag_rel, :notice => 'End point tag rel was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @end_point_tag_rel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /end_point_tag_rels/1
  # DELETE /end_point_tag_rels/1.xml
  def destroy
    @end_point_tag_rel = EndPointTagRel.find(params[:id])
    @end_point_tag_rel.destroy

    respond_to do |format|
      format.html { redirect_to(end_point_tag_rels_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/end_point_tag_rels_helper.rb
module EndPointTagRelsHelper
end

app/views/end_point_tag_rels/_form.html.erb
<%= form_for(@end_point_tag_rel) do |f| %>
  <% if @end_point_tag_rel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@end_point_tag_rel.errors.count, "error") %> prohibited this end_point_tag_rel from being saved:</h2>

      <ul>
      <% @end_point_tag_rel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :endpoint_id %><br />
    <%= f.text_field :endpoint_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br />
    <%= f.text_field :tag_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/end_point_tag_rels/edit.html.erb
<h1>Editing end_point_tag_rel</h1>

<%= render 'form' %>

<%= link_to 'Show', @end_point_tag_rel %> |
<%= link_to 'Back', end_point_tag_rels_path %>

app/views/end_point_tag_rels/index.html.erb
<h1>Listing end_point_tag_rels</h1>

<table>
  <tr>
    <th>Endpoint</th>
    <th>Tag</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @end_point_tag_rels.each do |end_point_tag_rel| %>
  <tr>
    <td><%= end_point_tag_rel.endpoint_id %></td>
    <td><%= end_point_tag_rel.tag_id %></td>
    <td><%= end_point_tag_rel.status %></td>
    <td><%= link_to 'Show', end_point_tag_rel %></td>
    <td><%= link_to 'Edit', edit_end_point_tag_rel_path(end_point_tag_rel) %></td>
    <td><%= link_to 'Destroy', end_point_tag_rel, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New End point tag rel', new_end_point_tag_rel_path %>

app/views/end_point_tag_rels/new.html.erb
<h1>New end_point_tag_rel</h1>

<%= render 'form' %>

<%= link_to 'Back', end_point_tag_rels_path %>

app/views/end_point_tag_rels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Endpoint:</b>
  <%= @end_point_tag_rel.endpoint_id %>
</p>

<p>
  <b>Tag:</b>
  <%= @end_point_tag_rel.tag_id %>
</p>

<p>
  <b>Status:</b>
  <%= @end_point_tag_rel.status %>
</p>


<%= link_to 'Edit', edit_end_point_tag_rel_path(@end_point_tag_rel) %> |
<%= link_to 'Back', end_point_tag_rels_path %>