config/routes.rb
MeantIt::Application.routes.draw do

  get "/group/:pii_value_input" => "home#group"

  get "/shops/:id" => "shops#show"
  post "/payments/ipn_pp_20111224" => "payments#ipn"
  get "/payments/pay/invoice_no/:invoice_no" => "payments#pay"
  get "/payments/invoice_no/:invoice_no" => "payments#show"
  get "/payments/cancel/invoice_no/:invoice_no" => "payments#cancel"

  resources :payments

  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "verify_captcha" => "sessions#verify_captcha", :as => "verify_captcha"
  get "manage" => "sessions#manage", :as => "manage"
  get "resend_confirmation" => "sessions#resend_confirmation", :as => "resend_confirmation"
  get "send_liker_emails" => "sessions#send_liker_emails"
  get "bill" => "sessions#bill_2", :as => "bill_2"
  get "bills/error" => "sessions#bills_error"

  devise_for :users, :controllers => { :confirmations => "meant_it_confirmations" }

  resources :sessions

  resources :pii_property_sets

  resources :inbound_email_logs

  resources :yes_emails

  resources :meant_it_mood_tag_rels

  resources :entity_data

  resources :inbound_emails

  resources :end_point_tag_rels

  resources :tags

  resources :obj_rels

  resources :meant_it_rels do
    collection do
      get 'show_out_by_pii'
      get 'count_in_mirs'
      get 'show_in_by_pii'
      get 'show_out_by_endpoint_nick/:nick/(:message_type)', :action => 'show_out_by_endpoint_nick'
      get 'show_in_by_endpoint_nick/:nick/(:message_type)', :action => 'show_in_by_endpoint_nick'
      get 'show_out_by_endpoint_id/:id/(:message_type)', :action => 'show_out_by_endpoint_id'
      get 'show_in_by_endpoint_id/:id/(:message_type)', :action => 'show_in_by_endpoint_id'
      get 'show_by_endpoint_endpoint_nick/:nick1/:nick2/(:message_type)', :action => 'show_by_endpoint_endpoint_nick'
      get 'show_by_pii_pii' 
      get 'show_by_pii_endpoint_nick'
      get 'show_by_endpoint_nick_pii'
      get 'show_by_message_type'
    end
  end

  resources :entity_end_point_rels

  resources :end_points do
    collection do
      get 'show_by_nick/:nick', :action => "show_by_nick"
      get 'find_by_nick_and_creator_endpoint_id'
      get 'show_by_nick_and_creator_endpoint_id'
      get 'find_by_tags'
      get 'show_by_tags'
      get "show_by_id/:id", :action => "show_by_id"
      get "show_by_ids"
    end
  end

  resources :entities

  get 'piis/pii_property_set_limited/:pii_value_input' => "piis#pii_property_set_limited"

  resources :piis do
    collection do
      get 'find_by_pii_value'
      get 'find_by_pii_value_debug'
      get 'show_by_pii_value'
      get 'show_by_pii_value_debug'
      get 'show_by_message_type_uniq_sender_count'
      get 'show_like_pii_value_uniq_sender_count_after_last_bill'
      get 'show_like_pii_value_non_uniq_sender_count_after_last_bill'
    end
  end

  resources :people

  get "home/index"

  root :to => "home#index"
  match "/why" => "home#why"
  match "/message_types" => "home#message_types"
  match "/learn_find" => "home#learn_find"
  match "/learn_send" => "home#learn_send"
  match "/tutorial_1" => "home#tutorial_1"
  match "/group.html" => "home#group"
  match "/group_old.html" => "home#group_old"
  match "/group_diy.html" => "home#group_diy"
  match "/cafeshopping.html" => "home#cafeshopping"
  match "/like.html" => "home#like"
  match "/platform.html" => "home#platform"
  match "/apis.html" => "home#apis"
  match "/policy.html" => "home#policy"
  match "/campaigns/:name" => "home#campaigns"
  match "/campaigns/:predir/:name" => "home#campaigns"

  match "/receive_email" => ReceiveEmail

  match "/find_any" => FindAny.action(:index)

  match "/inbound_emails_200" => "inbound_emails#create", :defaults => { :format => 'xml' }
  match "/send_inbound_emails" => "inbound_emails#create"

end

app/views/shared/_bottom_menu.html.erb
<br/>
<div class="span-24">
  <div style="text-align:center"><%= link_to "Policy", "/policy.html" %></div>
</div>

app/views/shared/_end_point.html.erb
<% require 'constants' %>
<%
  creator_endPoint = nil
  creator_ident = nil
  if !end_point.nick.nil?
    creator_endPoint = EndPoint.find(end_point.creator_endpoint_id)
    creator_ident = creator_endPoint.nick.nil? ? creator_endPoint.id : creator_endPoint.nick
  end
%>
  <%= link_to "nick:#{end_point.nick}", "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(end_point.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{end_point.creator_endpoint_id}" %>
  <%= link_to "(own:#{creator_ident})", "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(creator_endPoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{end_point.creator_endpoint_id}" %>
<% if !end_point.pii.nil? %>
     <%= link_to "[pii:#{end_point.pii.pii_value}]", "#{show_by_pii_value_piis_url}?#{Constants::PII_VALUE_INPUT}=#{URI::encode(end_point.pii.pii_value)}" %>
<% end %>

app/views/shared/_end_point_nick_col.html.erb
<% require 'validators' %>
<%
  show_pii_force ||= false
  show_nick_force ||= false
  show_own_force ||= false
  # If not forced, the rules for display are:
  # - never shown if pii_hide is "true" (string not boolean)
  # - don't show pii unless pii_hide is "false"
  # - if we have not shown pii, then show nick, if it's not nil, otherwise show record number
  # - if we show nick, then show own
  #   AI:NICK#1: if nick == own then just show either
  #   AI:NICK#2: show as 'own's nick' instead of nick:<nick> (own:<own>)
  pii_shown = false
  nick_shown = false
%>
<%
  creator_endPoint = nil
  if !end_point_nick_col.nil?
    creator_endPoint = EndPoint.find(end_point_nick_col.creator_endpoint_id)
  end
%>
<%
#20110630a  if !end_point_nick_col.nil? and !end_point_nick_col.pii.nil? and (end_point_nick_col.pii.pii_type == PiiTypeValidator::PII_TYPE_GLOBAL)
  if !end_point_nick_col.nil? and !end_point_nick_col.pii.nil? and (end_point_nick_col.pii.pii_hide == "false")
    pii_shown = true
%>
     <%= link_to "[#{end_point_nick_col.pii.pii_value}]", "#{show_by_pii_value_piis_url}?#{Constants::PII_VALUE_INPUT}=#{URI::encode(end_point_nick_col.pii.pii_value)}" %>
<% end %>
<% 
  if !end_point_nick_col.nil? and (show_nick_force or !pii_shown)
    nick_shown = true
    if !end_point_nick_col.nick.nil?
      # Prepare links for nick
      nick_link_to = "#{end_point_nick_col.nick}"
      nick_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(end_point_nick_col.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{end_point_nick_col.creator_endpoint_id}"
%>
<%
    else
      # Prepare links for nick
      nick_link_to = ControllerHelper.ai_for_endpoint(end_point_nick_col, "nick_")
      nick_url = "/end_points/show_by_id/#{end_point_nick_col.id}"
%>
<% 
    end 
  end
%>
<% if !creator_endPoint.nil? and nick_shown
     if !creator_endPoint.nick.nil?
       own_link_to = "(#{creator_endPoint.nick})"
       own_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(creator_endPoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{end_point_nick_col.creator_endpoint_id}"
     else
       own_link_to = ControllerHelper.ai_for_endpoint(creator_endPoint, "own_")
       own_url = "/end_points/show_by_id/#{creator_endPoint.id}"
     end # end if !creator_endPoint.nick.nil?
     # AI:NICK#1
     if end_point_nick_col.nick != creator_endPoint.nick
%>
       <%
         if pii_shown
       %>
         aka 
       <%
         end # end if pii_shown
       %>
       <%= link_to "#{own_link_to}", "#{own_url}" %>'s
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<% 
     else
%>
       <%
         if pii_shown
       %>
         aka 
       <%
         end # end if pii_shown
       %>
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<% 
     end # end if end_point_nick_col.nick != creator_endPoint.nick
  end
 %>

app/views/shared/_end_point_pii_col.html.erb
<% if !end_point_pii_col.pii.nil? %>
   <%= link_to "#{end_point_pii_col.pii.pii_value}", "#{show_by_pii_value_piis_url}?#{Constants::PII_VALUE_INPUT}=#{URI::encode(end_point_pii_col.pii.pii_value)}" %>
<% end %>

app/views/shared/_meant_it_rel.html.erb
<% require 'validators' %>
<% require 'controller_helper' %>

<%
  show_pii_these ||= []
  show_pii_force ||= false
  show_nick_force ||= false
  show_own_force ||= false
  # If not forced, the rules for display are:
  # - never shown if pii_hide is "true" (string not boolean)
  # - don't show pii unless pii_hide is "false"
  # - if we have not shown pii, then show nick, if it's not nil, otherwise show record number
  # - if we show nick, then show own
  #   AI:NICK#1: if nick == own then just show either
  #   AI:NICK#2: show as 'own's nick' instead of nick:<nick> (own:<own>)
  src_pii_shown = false
  src_nick_shown = false
  dst_pii_shown = false
  dst_nick_shown = false
%>
<% #DEBUG Add meant_it_rel.id here to see which mirs are displayed %>
<%
  src_creator_endPoint = nil
#20110630a  if !meant_it_rel.src_endpoint.nil? and !meant_it_rel.src_endpoint.nick.nil?
  if !meant_it_rel.src_endpoint.nil?
    src_creator_endPoint = EndPoint.find(meant_it_rel.src_endpoint.creator_endpoint_id)
  end
%>
<% 
  if !meant_it_rel.src_endpoint.nil? and !meant_it_rel.src_endpoint.pii.nil? and (meant_it_rel.src_endpoint.pii.pii_hide == "false" or show_pii_force or !show_pii_these.index(meant_it_rel.src_endpoint.pii.pii_value).nil? )
    src_pii_shown = true
%>
     <%= link_to "[#{ControllerHelper.ai_for_pii(meant_it_rel.src_endpoint.pii)}]", "#{show_by_pii_value_piis_url}?#{Constants::PII_VALUE_INPUT}=#{URI::encode(meant_it_rel.src_endpoint.pii.pii_value)}" %>
<% end %>
<% 
  if !meant_it_rel.src_endpoint.nil? and (show_nick_force or !src_pii_shown)
    src_nick_shown = true
    if !meant_it_rel.src_endpoint.nick.nil?
      # Prepare links for nick
      nick_link_to = "#{meant_it_rel.src_endpoint.nick}"
      nick_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(meant_it_rel.src_endpoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{meant_it_rel.src_endpoint.creator_endpoint_id}"
%>
<%
    else
      nick_link_to = ControllerHelper.ai_for_endpoint(meant_it_rel.src_endpoint, "nick_")
      # Prepare links for nick
      nick_url = "/end_points/show_by_id/#{meant_it_rel.src_endpoint.id}"
%>
<% 
    end 
  end
%>
<% if !src_creator_endPoint.nil? and src_nick_shown
     if !src_creator_endPoint.nick.nil?
       own_link_to = "(#{src_creator_endPoint.nick})"
       own_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(src_creator_endPoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{meant_it_rel.src_endpoint.creator_endpoint_id}"
     else
       own_link_to = ControllerHelper.ai_for_endpoint(src_creator_endPoint, "own_")
       own_url = "#{end_point_path(src_creator_endPoint.id)}"
     end # end if !src_creator_endPoint.nick.nil?
     # AI:NICK#1
     if meant_it_rel.src_endpoint.nick != src_creator_endPoint.nick
%>
       <%= link_to "#{own_link_to}", "#{own_url}" %>'s
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<% 
     else
%>
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<%
     end # end if meant_it_rel.src_endpoint.nick != src_creator_endPoint.nick
  end
 %>

<b><%= meant_it_rel.message_type %></b>
<%
  dst_creator_endPoint = nil
#20110630a  if !meant_it_rel.dst_endpoint.nil? and !meant_it_rel.dst_endpoint.nick.nil?
  if !meant_it_rel.dst_endpoint.nil?
    dst_creator_endPoint = EndPoint.find(meant_it_rel.dst_endpoint.creator_endpoint_id)
  end
%>
<% 
  if !meant_it_rel.dst_endpoint.nil? and !meant_it_rel.dst_endpoint.pii.nil? and (meant_it_rel.dst_endpoint.pii.pii_hide == "false" or show_pii_force or !show_pii_these.index(meant_it_rel.src_endpoint.pii.pii_value).nil?)
    dst_pii_shown = true
%>
  <%= link_to "[#{ControllerHelper.ai_for_pii(meant_it_rel.dst_endpoint.pii)}]", "#{show_by_pii_value_piis_url}?#{Constants::PII_VALUE_INPUT}=#{URI::encode(meant_it_rel.dst_endpoint.pii.pii_value)}" %>
<% end %>
<% 
  if !meant_it_rel.dst_endpoint.nil? and (show_nick_force or !dst_pii_shown)
    dst_nick_shown = true
    if !meant_it_rel.dst_endpoint.nick.nil?
      # Prepare links for nick
      nick_link_to = "#{meant_it_rel.dst_endpoint.nick}"
      nick_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(meant_it_rel.dst_endpoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{meant_it_rel.dst_endpoint.creator_endpoint_id}"
%>
<%
    else
      nick_link_to = ControllerHelper.ai_for_endpoint(meant_it_rel.dst_endpoint, "nick_")
      # Prepare links for nick
      nick_url = "/end_points/show_by_id/#{meant_it_rel.dst_endpoint.id}"
%>
<% 
    end 
  end
%>
<% if !dst_creator_endPoint.nil? and dst_nick_shown
     if !dst_creator_endPoint.nick.nil?
       own_link_to = "(#{dst_creator_endPoint.nick})"
       own_url = "#{show_by_nick_and_creator_endpoint_id_end_points_url}?#{Constants::END_POINT_NICK_INPUT}=#{URI::encode(dst_creator_endPoint.nick)}&#{Constants::END_POINT_CREATOR_END_POINT_INPUT}=#{meant_it_rel.dst_endpoint.creator_endpoint_id}"
     else
       own_link_to = ControllerHelper.ai_for_endpoint(dst_creator_endPoint, "own_")
       own_url = "#{end_point_path(dst_creator_endPoint.id)}"
     end # end if !dst_creator_endPoint.nick.nil?
     # AI:NICK#1
     if meant_it_rel.dst_endpoint.nick != dst_creator_endPoint.nick
%>
       <%= link_to "#{own_link_to}", "#{own_url}" %>'s
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<% 
     else
%>
       <%= link_to "#{nick_link_to}", "#{nick_url}" %>
<%
     end # end if meant_it_rel.dst_endpoint.nick != dst_creator_endPoint.nick
  end
%>

<% 
  if !meant_it_rel.message.nil? and !meant_it_rel.message.empty?
    if meant_it_rel.message.size > Constants::MESSAGE_DISPLAY_LEN
      truncated_message = "#{meant_it_rel.message[0, Constants::MESSAGE_DISPLAY_LEN]}..."
    else
      truncated_message = meant_it_rel.message
    end # end if meant_it_rel.message.size > #{Constants::MESSAGE_DISPLAY_LEN}
%>

  <%= ControllerHelper.random_say %> <b>'<i><%= truncated_message %></i>'</b>
<% end %>

<% 
  time_ago_str = time_ago_in_words(meant_it_rel.created_at)
  new_str = ''
  if time_ago_str.match(/less than a minute/) or time_ago_str.match(/^[1-2] minute/)
    new_str = "<span style='color:red;font-weight:bold;'>New!</span>"
  end # end if time_ago_str.match(/less than a minute/)
%>
- <%= time_ago_str %> ago <%= raw(new_str) %>

app/views/shared/_top_menu.html.erb
<% show_new_user ||= nil %>
<% no_login_form ||= false %>
<div class="span-20">
  <%= link_to "Home", url_for("/") %>
  <% if current_entity %>
    <%= link_to "Manage", manage_path %>
    <% if current_entity.property_document_id.nil? %>
      <%= link_to "Profile", new_entity_datum_path %>
    <% else %>
      <%= link_to "Profile", edit_entity_datum_path(current_entity.property_document_id) %>
    <% end %>
    <%= link_to "Log out", log_out_path %>
    Logged in as <b><%= current_entity.login_name %></b>
  <% elsif no_login_form %>
    <!--- Don't show anything --->
  <% elsif show_new_user.nil? %>
    <form style='display:inline' accept-charset='UTF-8' action='/sessions' class='session_new' id='session_new' method='post'>
      Login name:<input type='text' id='session_login_name' name='session[login_name]' size='15'/>
      Password:<input type='password' id='session_password' name='session[password]' size='15'/>
      <input id="session_submit" name="commit" type="submit" value="Sign In/Up" />
    </form>
  <% else %>
    About to create new user <b><%= show_new_user %></b>
    <form method='get' action='<%= verify_captcha_path %>'>
      <%= recaptcha_tags %>
      <input type='hidden' id='session_login_name' name='session[login_name]' value='<%= show_new_user %>'/>
      <input type='hidden' id='session_password' name='session[password]' value='<%= show_pword %>'/>
    </form>
  <% end %>
  <% 
    error_msg ||= nil
    if error_msg
  %>
    <p id="error" class="large"><b>Error:</b> <%= error_msg  %></p>
  <% elsif flash[:notice] %>
    <p id="info" class="large"><b>Notice:</b> <%= flash[:notice] %></p>
  <% elsif flash[:alert] %>
    <p id="error" class="large"><b>Alert:</b> <%= flash[:alert] %></p>
  <% elsif flash[:error] %>
    <p id="error" class="large"><b>Error:</b> <%= flash[:error] %></p>
  <% else %>
    <p class="large"> &nbsp; </p>
  <% end %>
</div>
<div class="span-4 last">
  <img height='20' src='/images/nethseven_meant_it.png' />
  <a href='http://twitter.com/nethseven'>twitter.com/nethseven</a><br />
  <a href='http://getsatisfaction.com/meant_it'>Get Help!</a><br />
  <a href='/platform.html'>Build an app</a>
</div>