config/routes.rb
MeantIt::Application.routes.draw do

  get "/group/:pii_value_input" => "home#group"

  get "/shops/:id" => "shops#show"
  post "/payments/ipn_pp_20111224" => "payments#ipn"
  get "/payments/pay/invoice_no/:invoice_no" => "payments#pay"
  get "/payments/invoice_no/:invoice_no" => "payments#show"
  get "/payments/cancel/invoice_no/:invoice_no" => "payments#cancel"

  resources :payments

  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "verify_captcha" => "sessions#verify_captcha", :as => "verify_captcha"
  get "manage" => "sessions#manage", :as => "manage"
  get "resend_confirmation" => "sessions#resend_confirmation", :as => "resend_confirmation"
  get "send_liker_emails" => "sessions#send_liker_emails"
  get "bill" => "sessions#bill_2", :as => "bill_2"
  get "bills/error" => "sessions#bills_error"

  devise_for :users, :controllers => { :confirmations => "meant_it_confirmations" }

  resources :sessions

  resources :pii_property_sets

  resources :inbound_email_logs

  resources :yes_emails

  resources :meant_it_mood_tag_rels

  resources :entity_data

  resources :inbound_emails

  resources :end_point_tag_rels

  resources :tags

  resources :obj_rels

  resources :meant_it_rels do
    collection do
      get 'show_out_by_pii'
      get 'count_in_mirs'
      get 'show_in_by_pii'
      get 'show_out_by_endpoint_nick/:nick/(:message_type)', :action => 'show_out_by_endpoint_nick'
      get 'show_in_by_endpoint_nick/:nick/(:message_type)', :action => 'show_in_by_endpoint_nick'
      get 'show_out_by_endpoint_id/:id/(:message_type)', :action => 'show_out_by_endpoint_id'
      get 'show_in_by_endpoint_id/:id/(:message_type)', :action => 'show_in_by_endpoint_id'
      get 'show_by_endpoint_endpoint_nick/:nick1/:nick2/(:message_type)', :action => 'show_by_endpoint_endpoint_nick'
      get 'show_by_pii_pii' 
      get 'show_by_pii_endpoint_nick'
      get 'show_by_endpoint_nick_pii'
      get 'show_by_message_type'
    end
  end

  resources :entity_end_point_rels

  resources :end_points do
    collection do
      get 'show_by_nick/:nick', :action => "show_by_nick"
      get 'find_by_nick_and_creator_endpoint_id'
      get 'show_by_nick_and_creator_endpoint_id'
      get 'find_by_tags'
      get 'show_by_tags'
      get "show_by_id/:id", :action => "show_by_id"
      get "show_by_ids"
    end
  end

  resources :entities

  get 'piis/pii_property_set_limited/:pii_value_input' => "piis#pii_property_set_limited"

  resources :piis do
    collection do
      get 'find_by_pii_value'
      get 'find_by_pii_value_debug'
      get 'show_by_pii_value'
      get 'show_by_pii_value_debug'
      get 'show_by_message_type_uniq_sender_count'
      get 'show_like_pii_value_uniq_sender_count_after_last_bill'
      get 'show_like_pii_value_non_uniq_sender_count_after_last_bill'
    end
  end

  resources :people

  get "home/index"

  root :to => "home#index"
  match "/why" => "home#why"
  match "/message_types" => "home#message_types"
  match "/learn_find" => "home#learn_find"
  match "/learn_send" => "home#learn_send"
  match "/tutorial_1" => "home#tutorial_1"
  match "/group.html" => "home#group"
  match "/group_old.html" => "home#group_old"
  match "/group_diy.html" => "home#group_diy"
  match "/cafeshopping.html" => "home#cafeshopping"
  match "/like.html" => "home#like"
  match "/platform.html" => "home#platform"
  match "/apis.html" => "home#apis"
  match "/policy.html" => "home#policy"
  match "/campaigns/:name" => "home#campaigns"
  match "/campaigns/:predir/:name" => "home#campaigns"

  match "/receive_email" => ReceiveEmail

  match "/find_any" => FindAny.action(:index)

  match "/inbound_emails_200" => "inbound_emails#create", :defaults => { :format => 'xml' }
  match "/send_inbound_emails" => "inbound_emails#create"

end

app/models/end_point.rb
require 'validators'

class EndPoint < ActiveRecord::Base
#  alias_attribute :end_point_id, :endPoint_id
#  alias_attribute "endPoint_id" "end_point_id"

  has_many :dstMeantItRels, :foreign_key => "dst_endpoint_id", :class_name => "MeantItRel"
#  has_many :dstEndPoints, :through => :dstMeantItRels, :source => :dstEndPoint
  has_many :dstEndPoints, :through => :dstMeantItRels, :source => :dst_endpoint
  has_many :srcMeantItRels, :foreign_key => "src_endpoint_id", :class_name => "MeantItRel"
#  has_many :srcEndPoints, :through => :srcMeantItRels, :source => :srcEndPoint
  has_many :srcEndPoints, :through => :srcMeantItRels, :source => :src_endpoint
#  has_one :creatorEndPoint, :foreign_key => "createEndPoint_id", :class_name => "EndPoint"
  has_one :creatorEndPoint, :foreign_key => "creator_endoint_id", :class_name => "EndPoint"
#  has_one :pii, :foreign_key => '"endPoint_id"'
#20110628a  has_one :pii, :foreign_key => "endpoint_id"
  belongs_to :pii
#  has_many :objRels, :as => "srcObj"
  has_many :objRels, :as => "srcobj"
#  has_many :objRels, :as => "dstObj"
  has_many :objRels, :as => "dstobj"
#  has_many :endPointTagRels, :foreign_key => '"endPoint_id"', :class_name => "EndPointTagRel"
  has_many :endPointTagRels, :foreign_key => "endpoint_id", :class_name => "EndPointTagRel"
  has_many :tags, :through => :endPointTagRels
#  has_many :entityEndPointRels, :foreign_key => '"endPoint_id"'
  has_many :entityEndPointRels, :foreign_key => "endpoint_id"
  has_many :entities, :through => :entityEndPointRels

  belongs_to :creatorEndPoint, :class_name => "EndPoint"

#  validates :nick, :presence => true
#  validates :startTime, :presence => true
  validates :start_time, :presence => true
  validates :status, :presence => true, :status_type => true

  after_initialize :default_values

  # Find intersection of tags
  def EndPoint.tagged(tg, *tgs)
    tgs_raw = tgs.unshift(*tg)
    tgs = tgs_raw.collect { |raw_elem| raw_elem.gsub(/\\/, '\&\&').gsub(/'/, "''") }
    joins(:tags).where("lower(tags.name) = '" + 
      tgs.uniq.collect{ |t| t.to_s.downcase }.join("' OR lower(tags.name) = '") + 
      "'").group("end_points.id", "end_points.creator_endpoint_id", 
      "end_points.nick", "end_points.start_time", "end_points.end_time", 
      "end_points.created_at", "end_points.updated_at", 
      "end_points.pii_id",
      "end_points.status").having("count(end_points.id) = #{tgs.count}")
  end # end def EndPoint.tagged

  private
    def default_values
      self.status||= StatusTypeValidator::STATUS_ACTIVE
    end
end

app/controllers/end_points_controller.rb
require 'controller_helper'
require 'constants'

class EndPointsController < ApplicationController
#  before_filter :authorize, :except => [:index, :show, :create, :show_by_nick, :show_by_ids, :show_by_id, :show_by_nick_and_creator_endpoint_id, :show_by_tags ]
  before_filter :authorize, :except => [:create, :show_by_nick, :show_by_ids, :show_by_id, :show_by_nick_and_creator_endpoint_id, :show_by_tags ]

  # GET /end_points
  # GET /end_points.xml
  def index
    @end_points = EndPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @end_points }
    end
  end

  # GET /end_points/1
  # GET /end_points/1.xml
  def show
    @end_point = EndPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @end_point }
    end
  end

  # GET /end_points/new
  # GET /end_points/new.xml
  def new
    @end_point = EndPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @end_point }
    end
  end

  # GET /end_points/1/edit
  def edit
    @end_point = EndPoint.find(params[:id])
  end

  # POST /end_points
  # POST /end_points.xml
  def create
    @end_point = EndPoint.new(params[:end_point])

    respond_to do |format|
      if @end_point.save
        format.html { redirect_to(@end_point, :notice => 'End point was successfully created.') }
        format.xml  { render :xml => @end_point, :status => :created, :location => @end_point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @end_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /end_points/1
  # PUT /end_points/1.xml
  def update
    @end_point = EndPoint.find(params[:id])

    respond_to do |format|
      if @end_point.update_attributes(params[:end_point])
        format.html { redirect_to(@end_point, :notice => 'End point was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @end_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /end_points/1
  # DELETE /end_points/1.xml
  def destroy
    @end_point = EndPoint.find(params[:id])
    @end_point.destroy

    respond_to do |format|
      format.html { redirect_to(end_points_url) }
      format.xml  { head :ok }
    end
  end

  def show_by_nick
    logtag = ControllerHelper.gen_logtag
    end_point_nick = params[:nick]
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_nick:#{logtag}, end_point_nick:#{end_point_nick}")
    decoded_end_point_nick_input = URI::decode(end_point_nick)
    decoded_end_point_nick_input.chomp!
    decoded_end_point_nick_input.strip!
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_nick:#{logtag}, decoded_end_point_nick_input:#{decoded_end_point_nick_input}")
    @endPoint_arr = EndPoint.where("nick = ?", decoded_end_point_nick_input)

    respond_to do |format|
      format.html { render "show_end_points_same_nick", :layout => "find_any", :locals => { :find_any_input => decoded_end_point_nick_input } }
      format.xml  { render :xml => @endPoint_arr }
    end
  end # end def show_by_nick

  def show_by_ids
    logtag = ControllerHelper.gen_logtag
    title_str = params[Constants::TITLE_STR.to_sym]
    id_arr = params[:ids]
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_ids:#{logtag}, id_arr.inspect:#{id_arr.inspect}")
    @endPoint_arr = []
    id_arr.each { |id_no|
      @endPoint_arr << EndPoint.find(id_no)
    } # end id_arr.each { |id_no|

    respond_to do |format|
      format.html { render "show_end_points", :layout => "find_any", :locals => { :find_any_input => nil, :title_str => title_str } }
      format.xml  { render :xml => @endPoint_arr }
    end
  end # end def show_by_ids

  def show_by_id
    logtag = ControllerHelper.gen_logtag
    @endPoint = EndPoint.find(params[:id])
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_id:#{logtag}, @endPoint:#{@endPoint.inspect}")

    respond_to do |format|
      format.html { render "show_end_point_details", :layout => "find_any", :locals => { :find_any_input => nil } }
      format.xml  { render :xml => @endPoint }
    end
  end # end def show_by_id

  def show_by_nick_and_creator_endpoint_id
    logtag = ControllerHelper.gen_logtag
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_nick_and_creator_endpoint_id:#{logtag}, params[Constants::END_POINT_NICK_INPUT]:#{params[Constants::END_POINT_NICK_INPUT]}")
    end_point_nick = params[Constants::END_POINT_NICK_INPUT]
    decoded_end_point_nick_input = URI::decode(end_point_nick)
    decoded_end_point_nick_input.chomp!
    decoded_end_point_nick_input.strip!
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_nick_and_creator_endpoint_id:#{logtag}, params[Constants::END_POINT_CREATOR_END_POINT_INPUT]:#{params[Constants::END_POINT_CREATOR_END_POINT_INPUT]}")
    end_point_creator_end_point = params[Constants::END_POINT_CREATOR_END_POINT_INPUT]
    end_point_creator_end_point_id = end_point_creator_end_point.to_i 
    @endPoint = nil
    @endPoint = EndPoint.find_by_nick_and_creator_endpoint_id(decoded_end_point_nick_input, end_point_creator_end_point_id) if !decoded_end_point_nick_input.nil? and !end_point_creator_end_point_id.nil?
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_nick_and_creator_endpoint_id:#{logtag}, @endPoint:#{@endPoint.inspect}")

    respond_to do |format|
      format.html { render "show_end_point_details", :layout => "find_any", :locals => { :find_any_input => decoded_end_point_nick_input } }
      format.xml  { render :xml => @endPoint }
    end
  end # end def show_by_nick_and_creator_endpoint_id

  def show_by_tags
    logtag = ControllerHelper.gen_logtag
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_tags:#{logtag}, params[Constants::TAGS_INPUT]:#{params[Constants::TAGS_INPUT]}")
    tags_input = params[Constants::TAGS_INPUT]
    decoded_tags_input = URI::decode(tags_input)
    decoded_tags_input.chomp!
    decoded_tags_input.strip!
    decoded_tags_arr = decoded_tags_input.split if !decoded_tags_input.nil?
    @endPoint_arr = nil
    @endPoint_arr = EndPoint.tagged(decoded_tags_arr) if !decoded_tags_input.nil?
    logger.info("#{File.basename(__FILE__)}:#{self.class}:show_by_tags:#{logtag}, @endPoint_arr:#{@endPoint_arr.inspect}")

    respond_to do |format|
      format.html { render "show_end_points", :layout => "find_any", :locals => { :find_any_input => decoded_tags_input, :title_str => "End point(s) with <b>tag(s)</b>: <i>#{decoded_tags_input}</i>" } }
      format.xml  { render :xml => @endPoint_arr }
    end
  end

  def find_by_tags
    respond_to do |format|
      format.html # find_by_tags.html.erb
      format.xml  { render :xml => @endPoint_arr }
    end
  end

  def find_by_nick_and_creator_endpoint_id
    respond_to do |format|
      format.html # find_by_nick_and_creator_endpoint_id.html.erb
      format.xml  { render :xml => @endPoint_arr }
    end
  end
end

app/helpers/end_points_helper.rb
module EndPointsHelper
end

app/views/end_points/_form.html.erb
<%= form_for(@end_point) do |f| %>
  <% if @end_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@end_point.errors.count, "error") %> prohibited this end_point from being saved:</h2>

      <ul>
      <% @end_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creator_endpoint_id %><br />
    <%= f.text_field :creator_endpoint_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :pii_id %><br />
    <%= f.text_field :pii_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/end_points/edit.html.erb
<h1>Editing end_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @end_point %> |
<%= link_to 'Back', end_points_path %>

app/views/end_points/find_by_nick_and_creator_endpoint_id.html.erb
<% require 'constants' %>
<p id="notice"><%= notice %></p>
<form method='get' action='<%= show_by_nick_and_creator_endpoint_id_end_points_url %>'>
  <div>
    Nick: 
    <input type='text' name='<%= Constants::END_POINT_NICK_INPUT %>'/>
  </div>
  <div>
    Creator Endpoint Id:
    <input type='text' name='<%= Constants::END_POINT_CREATOR_END_POINT_INPUT %>'/>
  </div>
  <div class='actions'>
    <input type='submit'/>
  </div>
</form>

app/views/end_points/find_by_tags.html.erb
<% require 'constants' %>
<p id="notice"><%= notice %></p>
<form method='get' action='<%= show_by_tags_end_points_url %>'>
  <div>
    Tags: 
    <input type='text' name='<%= Constants::TAGS_INPUT %>'/>
  </div>
  <div class='actions'>
    <input type='submit'/>
  </div>
</form>

app/views/end_points/index.html.erb
<h1>Listing end_points</h1>

<table>
  <tr>
    <th>Creatorendpoint</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th>Nick</th>
    <th>Pii</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @end_points.each do |end_point| %>
  <tr>
    <td><%= end_point.creator_endpoint_id %></td>
    <td><%= end_point.start_time %></td>
    <td><%= end_point.end_time %></td>
    <td><%= end_point.nick %></td>
    <td><%= end_point.pii_id %></td>
    <td><%= end_point.status %></td>
    <td><%= link_to 'Show', end_point %></td>
    <td><%= link_to 'Edit', edit_end_point_path(end_point) %></td>
    <td><%= link_to 'Destroy', end_point, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New End point', new_end_point_path %>

app/views/end_points/new.html.erb
<h1>New end_point</h1>

<%= render 'form' %>

<%= link_to 'Back', end_points_path %>

app/views/end_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Creatorendpoint:</b>
  <%= @end_point.creator_endpoint_id %>
</p>

<p>
  <b>Starttime:</b>
  <%= @end_point.start_time %>
</p>

<p>
  <b>Endtime:</b>
  <%= @end_point.end_time %>
</p>

<p>
  <b>Nick:</b>
  <%= @end_point.nick %>
</p>

<p>
  <b>Pii Id:</b>
  <%= @end_point.pii_id %>
</p>

<p>
  <b>Status:</b>
  <%= @end_point.status %>
</p>


<%= link_to 'Edit', edit_end_point_path(@end_point) %> |
<%= link_to 'Back', end_points_path %>

app/views/end_points/show_end_point_details.html.erb
<p id="notice"><%= notice %></p>

<%
#  srcMeantItRelTypeHash = {}
#  MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each { |mi_type|
#    srcMeantItRelTypeHash[mi_type] = []
#  } # end MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each ...
#  srcMeantItRelTypeUniqHash = {}
#  MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each { |mi_type|
#    srcMeantItRelTypeUniqHash[mi_type] = []
#  } # end MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each ...
#  dstMeantItRelTypeHash = {}
#  MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each { |mi_type|
#    dstMeantItRelTypeHash[mi_type] = []
#  } # end MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each ...
#  dstMeantItRelTypeUniqHash = {}
#  MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each { |mi_type|
#    dstMeantItRelTypeUniqHash[mi_type] = []
#  } # end MeantItMessageTypeValidator::MEANT_IT_MESSAGE_TYPE_ENUM.each ...

  endPoint = @endPoint
  srcMeantItRels = endPoint.srcMeantItRels
  srcMeantItRelDstUniqs = ControllerHelper.ep_from_mir_uniqDstEndPoints(srcMeantItRels)

  srcMeantItRelTypeHash = ControllerHelper.classified_mir_hash_on_message_type_from_mir(srcMeantItRels)

  srcMeantItRelTypeUniqHash = ControllerHelper.classified_mir_hash_on_message_type_from_classified_mir_hash_on_message_type_uniqDstEndPoints(srcMeantItRelTypeHash)

 dstMeantItRels = endPoint.dstMeantItRels
 dstMeantItRelDstUniqs = ControllerHelper.ep_from_mir_uniqSrcEndPoints(dstMeantItRels)

  dstMeantItRelTypeHash = ControllerHelper.classified_mir_hash_on_message_type_from_mir(dstMeantItRels)

  dstMeantItRelTypeUniqHash = ControllerHelper.classified_mir_hash_on_message_type_from_classified_mir_hash_on_message_type_uniqDstEndPoints(dstMeantItRelTypeHash)
%>

<div class='container'>
  <div class='span-24'>

<p>
  <b>Recipient:</b>
  <% if !endPoint.nil? %>
    <%= render :partial => "shared/end_point_nick_col", :collection => [endPoint] %>
  <% end %>
</p>

<table summary="Meant.It Received Table"  border="0" cellspacing="0" cellpadding="0">
  <caption><em>Meant.It Received</em></caption>
  <thead>
    <tr>
      <th class='span-12'>Meant.It Type</th>
      <th class='span-4'>Senders</th>
      <th class='span-4'>Unique Senders</th>
      <th class='span-4'>Value</th>
    </tr>
  </thead>
  <tbody>
<% dstMeantItRelTypeHash.each { |mi_type, mi_elem| %>
    <tr>
      <td>
         <% find_any_input_custom_str = "#{endPoint.nick} #{mi_type}" %>
         <%= link_to "#{mi_type}", url_for("/find_any?#{Constants::FIND_ANY_INPUT}=#{CGI.escape(find_any_input_custom_str)}")  %>
      </td>
      <td>
        <% if !dstMeantItRelTypeHash[mi_type].nil? %>
          <%= dstMeantItRelTypeHash[mi_type].size %>
        <% end %>
      </td>
      <td>
        <% if !dstMeantItRelTypeUniqHash[mi_type].nil? %>
          <% 
            query_str = "ids%5b%5d="
            src_endpoint_arr = dstMeantItRelTypeUniqHash[mi_type].collect{ |mi_elem_elem| mi_elem_elem.src_endpoint_id }
            query_str += src_endpoint_arr.join("&ids%5b%5d=")
            title_str = CGI.escape("Unique Senders to <b>Pii:</b>#{@endPoint.nick} and <b>Message Type</b>:#{mi_type}")
          %>
          <%= link_to "#{dstMeantItRelTypeUniqHash[mi_type].size}", url_for("/end_points/show_by_ids?#{query_str}&#{Constants::TITLE_STR}=#{title_str}") %>
        <% end %>
      </td>
      <td>
        Coming..
      </td>
    </tr>
<% } %>
  </tbody>
</table>
<% if dstMeantItRelTypeHash.empty? %>
<p>
Nothing yet... <b>Don't be disheartened.  They'll come!</b>
</p>
<% end %>
<p>
  <%= render :partial => "shared/limit_meant_it_rels_with_more", :locals => { :dst_endpoint_id => endPoint, :sender_endpoint => @endPoint } %>
</p>

<table summary="Meant.It Sent Table"  border="0" cellspacing="0" cellpadding="0">
  <caption><em>Meant.It Sent</em></caption>
  <thead>
    <tr>
      <th class='span-12'>Meant.It Type</th>
      <th class='span-4'>Receivers</th>
      <th class='span-4'>Unique Receivers</th>
      <th class='span-4'>Value</th>
    </tr>
  </thead>
  <tbody>
<% srcMeantItRelTypeHash.each { |mi_type, mi_elem| %>
    <tr>
      <td>
         <% find_any_input_custom_str = "#{endPoint.nick} #{mi_type}" %>
         <%= link_to "#{mi_type}", url_for("/find_any?#{Constants::FIND_ANY_INPUT}=#{CGI.escape(find_any_input_custom_str)}")  %>
      </td>
      <td>
        <% if !srcMeantItRelTypeHash[mi_type].nil? %>
          <%= srcMeantItRelTypeHash[mi_type].size %>
        <% end %>
      </td>
      <td>
        <% if !srcMeantItRelTypeUniqHash[mi_type].nil? %>
          <% 
            query_str = "ids%5b%5d="
            dst_endpoint_arr = srcMeantItRelTypeUniqHash[mi_type].collect{ |mi_elem_elem| mi_elem_elem.dst_endpoint_id }
            query_str += dst_endpoint_arr.join("&ids%5b%5d=")
            title_str = CGI.escape("Unique Receivers of <b>nick:</b>#{@endPoint.nick} and <b>message type</b>:#{mi_type}")
          %>
          <%= link_to "#{srcMeantItRelTypeUniqHash[mi_type].size}", url_for("/end_points/show_by_ids?#{query_str}&#{Constants::TITLE_STR}=#{title_str}") %>
        <% end %>
      </td>
      <td>
        Coming..
      </td>
    </tr>
<% } %>
  </tbody>
</table>
<% if srcMeantItRelTypeHash.empty? %>
<p>
Nothing yet... <b>Send a meant.it today!</b>
</p>
<% end %>
<p>
  <%= render :partial => "shared/limit_meant_it_rels_with_more", :locals => { :src_endpoint_id => endPoint, :sender_endpoint => @endPoint } %>
</p>

  </div>
</div>

app/views/end_points/show_end_points.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <div class='span-24'>

<% 
    title_str ||= nil
    if !title_str.nil? 
%>
    <p><%= raw raw_display_only_b_and_i(title_str) %></p>
  <% end %>
  <ul><li>
  <%= render :partial => "shared/end_point_nick_col", :collection => @endPoint_arr, :spacer_template => "shared/li_ruler", :locals => { :show_nick_force => true } %>
  </li></ul>

  </div>
</div>

app/views/end_points/show_end_points_same_nick.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <div class='span-24'>

  The folowing has <b><%= @endPoint_arr[0].nick %></b> as <i>nick</i>.  Choose one:</b><br/>
  <ul><li>
  <%= render :partial => "shared/end_point_nick_col", :collection => @endPoint_arr, :spacer_template => "shared/li_ruler", :locals => { :show_nick_force => true } %>
  </li></ul>

  </div>
</div>